#!/usr/bin/env python3
"""make_verify_index.py -- generate VERIFY_SCRIPTS_INDEX.md.

Walks 05_papers/ for every verify_J*.py and maps it to the paper folder it
lives in. Many scripts are named after the ORIGINAL J-number a paper carried
before the series was renumbered/reorganized, so the filename often does not
match its folder. That drift is harmless (each script is run by path and its
in-folder references are self-consistent) but it makes navigation confusing.
This index documents the mapping and flags the legacy-name cases, so the
mismatch is a known, navigable thing rather than silent drift.

    Run:  python make_verify_index.py     # from 05_papers/
"""
import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "VERIFY_SCRIPTS_INDEX.md")


def folder_jnum(path):
    """The J-number of the paper folder this path lives under (e.g. J43)."""
    for part in path.replace("\\", "/").split("/"):
        if re.fullmatch(r"J\d+", part):
            return part
    return "?"


def file_jnum(fn):
    m = re.match(r"verify_(J\d+)", fn)
    return m.group(1) if m else "?"


def first_doc_line(path):
    """A short 'what it checks' hint: first non-trivial docstring/comment line."""
    try:
        with io.open(path, encoding="utf-8") as f:
            head = f.read(2000)
    except Exception:
        return ""
    for ln in head.splitlines():
        s = ln.strip().strip('"').strip("'").strip("#").strip()
        if len(s) > 12 and not s.startswith(("import", "from", "#!/")):
            return re.sub(r"\s+", " ", s)[:90]
    return ""


def main():
    rows = []
    for root, _, files in os.walk(HERE):
        for fn in sorted(files):
            if re.match(r"verify_J\d+.*\.py$", fn):
                p = os.path.join(root, fn)
                rel = os.path.relpath(p, HERE).replace("\\", "/")
                fol, fil = folder_jnum(rel), file_jnum(fn)
                rows.append((fol, fil, rel, fol == fil, first_doc_line(p)))
    rows.sort(key=lambda r: (int(re.sub(r"\D", "", r[0]) or 0), r[2]))

    n = len(rows)
    n_mismatch = sum(1 for r in rows if not r[3])
    out = [
        "# Verification-scripts index",
        "",
        "*Auto-generated by `make_verify_index.py`. Do not edit by hand — rerun the script.*",
        "",
        f"Every `verify_J*.py` under `05_papers/`, mapped to the paper folder it lives in. "
        f"{n} scripts; **{n_mismatch}** carry a legacy filename that does not match their "
        f"folder (from before the series was renumbered). The drift is harmless — each script "
        f"is run by path (`python <path>`) and its in-folder references are self-consistent — "
        f"but this table is the key so it stays navigable. To run everything, use "
        f"`verification/VERIFY_ALL.py` (the aggregate rope-check), not these per-paper scripts.",
        "",
        "| Paper (folder) | Verifier file | Match? | Checks |",
        "|---|---|:---:|---|",
    ]
    for fol, fil, rel, ok, hint in rows:
        flag = "yes" if ok else f"**legacy `{fil}`**"
        out.append(f"| {fol} | `{rel}` | {flag} | {hint} |")
    out += [
        "",
        "## Note on the legacy names",
        "",
        "A `legacy` row means the script's filename keeps the J-number the paper had "
        "*before* renumbering; the science is unaffected. Two papers were made fully "
        "folder-consistent on 2026-09-22 (J43 → `verify_J43_S4_closure.py`, J29 → "
        "`verify_J29.py`) because their references were actually broken/wrong; the rest are "
        "left named-as-is and simply mapped here to avoid a large, low-value rename sweep.",
        "",
    ]
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"VERIFY_SCRIPTS_INDEX.md written: {n} scripts, {n_mismatch} legacy-named.")


if __name__ == "__main__":
    main()
