#!/usr/bin/env python3
# ============================================================
# verify_J30.py
#
# Verification for J30:
#   "The Multiplicative-Unit Sub-Magma C = (Z/10Z)* in the TSML
#    Composition Lattice, and Its Contrast with the Joint 4-Core
#    {0, 7, 8, 9}" (Sanders, Gish, 2026)
#
# Self-contained: stdlib only (itertools, collections).
# Runtime: << 1 second.
#
# Checks (J30-specific, per manuscript Section / Theorem map):
#   1. (Z/10Z)* = {1, 3, 7, 9} is closed under ordinary
#      multiplication mod 10 (Lemma 2.2 sub-magma check).
#   2. (Z/10Z)* is a cyclic group of order 4, generated by 3:
#      3^1=3, 3^2=9, 3^3=7, 3^4=1 (Lemma 2.2).
#   3. CL_TSML restricted to C x C: image = {3, 7}, distribution
#      14 cells of 7 and 2 cells of 3, located at (3, 9), (9, 3)
#      (Theorem 3.1).
#   4. CL_BHML restricted to C x C: image = {0, 2, 4, 6, 8},
#      disjoint from C; distribution 3 of 0, 3 of 2, 5 of 4,
#      4 of 6, 1 of 8 (Proposition 4.1).
#   5. Among the 210 size-4 subsets of Z/10Z, exactly 78 are
#      CL_TSML-closed, all containing HARMONY = 7; exactly 1 is
#      CL_BHML-closed and 1 is jointly closed: the 4-core
#      {0, 7, 8, 9} (Theorem 4.3).
#   6. C is not (Z/10Z)*-equivalent to the joint 4-core: the
#      intersection C ∩ {0, 7, 8, 9} = {7, 9}.
#   7. Generator selection (Theorem 5.1): of the two primitive
#      roots g in {3, 7} of (Z/10Z)*, only g = 3 satisfies
#      g^3 = 7 (giving T* = 5/7 < 1); g = 7 gives 7^3 = 3
#      (T* = 5/3 > 1).
#   8. CREATION orbit 1 -> 3 -> 9 -> 7 -> 1 under x3 (Remark 2.3).
#   9. DISSOLUTION orbit 2 -> 6 -> 8 -> 4 -> 2 under x3
#      (Remark 2.3).
#
# Run: python verify_J30.py
# ============================================================

from itertools import combinations
from collections import Counter


# -- the two 10x10 tables (verbatim from companion verification) --
CL_TSML = [
    [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
    [0, 7, 3, 7, 7, 7, 7, 7, 7, 7],
    [0, 3, 7, 7, 4, 7, 7, 7, 7, 9],
    [0, 7, 7, 7, 7, 7, 7, 7, 7, 3],
    [0, 7, 4, 7, 7, 7, 7, 7, 8, 7],
    [0, 7, 7, 7, 7, 7, 7, 7, 7, 7],
    [0, 7, 7, 7, 7, 7, 7, 7, 7, 7],
    [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
    [0, 7, 7, 7, 8, 7, 7, 7, 7, 7],
    [0, 7, 9, 3, 7, 7, 7, 7, 7, 7],
]

CL_BHML = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6, 7, 2, 6, 6],
    [2, 3, 3, 4, 5, 6, 7, 3, 6, 6],
    [3, 4, 4, 4, 5, 6, 7, 4, 6, 6],
    [4, 5, 5, 5, 5, 6, 7, 5, 7, 7],
    [5, 6, 6, 6, 6, 6, 7, 6, 7, 7],
    [6, 7, 7, 7, 7, 7, 7, 7, 7, 7],
    [7, 2, 3, 4, 5, 6, 7, 8, 9, 0],
    [8, 6, 6, 6, 7, 7, 7, 9, 7, 8],
    [9, 6, 6, 6, 7, 7, 7, 0, 8, 0],
]

C = (1, 3, 7, 9)             # the corner = (Z/10Z)*
FOURCORE = (0, 7, 8, 9)      # joint 4-core
HARMONY = 7


def is_closed(S, table):
    """S is a sub-magma of `table` iff table[i][j] in S for all i,j in S."""
    Sset = set(S)
    return all(table[i][j] in Sset for i in S for j in S)


def hr(label):
    print()
    print("=" * 60)
    print(label)
    print("=" * 60)


# === Check 1: (Z/10Z)* closed under x mod 10 ===
def check_units_closed_mod10():
    hr("Check 1: (Z/10Z)* = {1,3,7,9} closed under x mod 10")
    image = set()
    for i in C:
        for j in C:
            image.add((i * j) % 10)
    ok = image.issubset(set(C))
    print(f"  image of C x C under x mod 10: {sorted(image)}")
    print(f"  subset of C = {{1, 3, 7, 9}}: {ok}")
    return ok


# === Check 2: cyclic group of order 4, generator g = 3 ===
def check_cyclic_generator():
    hr("Check 2: (Z/10Z)* is cyclic of order 4, generated by 3")
    powers = []
    g = 3
    x = 1
    for _ in range(4):
        x = (x * g) % 10
        powers.append(x)
    expected = [3, 9, 7, 1]
    ok = powers == expected
    print(f"  3^k for k = 1..4 (mod 10): {powers}")
    print(f"  expected [3, 9, 7, 1]: {ok}")
    return ok


# === Check 3: CL_TSML restricted to C x C ===
def check_tsml_on_C():
    hr("Check 3: CL_TSML restricted to C x C (Theorem 3.1)")
    cells = [CL_TSML[i][j] for i in C for j in C]
    image = set(cells)
    dist = Counter(cells)
    closed = is_closed(C, CL_TSML)

    # Locate the two PROGRESS (value-3) cells
    three_cells = [(i, j) for i in C for j in C if CL_TSML[i][j] == 3]

    print(f"  16-cell image: {sorted(image)}")
    print(f"  cell distribution: {dict(sorted(dist.items()))}")
    print(f"  PROGRESS-cell locations (value 3): {three_cells}")
    print(f"  C is TSML-closed: {closed}")

    ok = (
        closed
        and image == {3, 7}
        and dist[7] == 14
        and dist[3] == 2
        and set(three_cells) == {(3, 9), (9, 3)}
    )
    print(f"  Theorem 3.1 verified: {ok}")
    return ok


# === Check 4: CL_BHML restricted to C x C ===
def check_bhml_on_C():
    hr("Check 4: CL_BHML restricted to C x C (Proposition 4.1)")
    cells = [CL_BHML[i][j] for i in C for j in C]
    image = set(cells)
    dist = Counter(cells)
    closed = is_closed(C, CL_BHML)

    # Explicit witness from the manuscript (Proposition 4.1 proof)
    witness = CL_BHML[1][1]

    print(f"  CL_BHML[1][1] = {witness}; in C? {witness in C}")
    print(f"  16-cell image: {sorted(image)}")
    print(f"  disjoint from C: {image.isdisjoint(set(C))}")
    print(f"  cell distribution: {dict(sorted(dist.items()))}")
    print(f"  C is BHML-closed: {closed}")

    ok = (
        not closed
        and image == {0, 2, 4, 6, 8}
        and image.isdisjoint(set(C))
        and dist[0] == 3
        and dist[2] == 3
        and dist[4] == 5
        and dist[6] == 4
        and dist[8] == 1
        and witness == 2
    )
    print(f"  Proposition 4.1 verified: {ok}")
    return ok


# === Check 5: size-4 subset enumeration ===
def check_size4_enumeration():
    hr("Check 5: size-4 closed subsets (Theorem 4.3)")
    tsml_closed = []
    bhml_closed = []
    joint_closed = []
    total = 0
    for S in combinations(range(10), 4):
        total += 1
        t = is_closed(S, CL_TSML)
        b = is_closed(S, CL_BHML)
        if t:
            tsml_closed.append(S)
        if b:
            bhml_closed.append(S)
        if t and b:
            joint_closed.append(S)

    n_tsml = len(tsml_closed)
    n_bhml = len(bhml_closed)
    n_joint = len(joint_closed)
    all_tsml_contain_7 = all(HARMONY in S for S in tsml_closed)
    C_is_tsml = tuple(sorted(C)) in tsml_closed

    print(f"  total size-4 subsets of Z/10Z: {total} (expected 210)")
    print(f"  TSML-closed size-4 subsets: {n_tsml} (expected 78)")
    print(f"  all 78 contain HARMONY = 7: {all_tsml_contain_7}")
    print(f"  BHML-closed size-4 subsets: {n_bhml} (expected 1)")
    print(f"  jointly closed size-4 subsets: {n_joint} (expected 1)")
    print(f"  unique BHML-closed 4-subset: "
          f"{bhml_closed[0] if bhml_closed else None}")
    print(f"  unique joint-closed 4-subset: "
          f"{joint_closed[0] if joint_closed else None}")
    print(f"  C = {{1,3,7,9}} is among the 78 TSML-closed: {C_is_tsml}")

    ok = (
        total == 210
        and n_tsml == 78
        and n_bhml == 1
        and n_joint == 1
        and bhml_closed[0] == FOURCORE
        and joint_closed[0] == FOURCORE
        and all_tsml_contain_7
        and C_is_tsml
    )
    print(f"  Theorem 4.3 verified: {ok}")
    return ok


# === Check 6: C vs the joint 4-core ===
def check_contrast():
    hr("Check 6: C vs joint 4-core: C is NOT (Z/10Z)*-equivalent")
    inter = set(C) & set(FOURCORE)
    print(f"  C = {{1, 3, 7, 9}}")
    print(f"  joint 4-core = {FOURCORE}")
    print(f"  intersection: {sorted(inter)} (expected {{7, 9}})")
    print(f"  C != joint 4-core: {set(C) != set(FOURCORE)}")
    # Empty intersection beyond {7, 9}: i.e. {1, 3} subset C \ joint
    # and {0, 8} subset joint \ C.
    only_C = set(C) - set(FOURCORE)
    only_joint = set(FOURCORE) - set(C)
    print(f"  C \\ joint 4-core: {sorted(only_C)} (expected {{1, 3}})")
    print(f"  joint 4-core \\ C: {sorted(only_joint)} (expected {{0, 8}})")
    ok = (
        inter == {7, 9}
        and only_C == {1, 3}
        and only_joint == {0, 8}
    )
    print(f"  Contrast verified: {ok}")
    return ok


# === Check 7: generator selection g = 3 (Theorem 5.1) ===
def check_generator_selection():
    hr("Check 7: Generator selection g = 3 (Theorem 5.1)")
    g3_cubed = (3 ** 3) % 10
    g7_cubed = (7 ** 3) % 10
    BALANCE = 5

    # T* = BALANCE / HARMONY where HARMONY := g^3 (mod 10).
    # We do not compute the rational; we check the inequality
    # BALANCE < g^3 (mod 10) for g = 3 and BALANCE > g^3 for g = 7.
    print(f"  3^3 mod 10 = {g3_cubed} (expected 7 = HARMONY)")
    print(f"  7^3 mod 10 = {g7_cubed} (expected 3 = PROGRESS)")
    print(f"  BALANCE = 5")
    print(f"  Under g = 3: T* = 5/7 in (0, 1): {BALANCE < g3_cubed}")
    print(f"  Under g = 7: T* = 5/3 > 1:       {BALANCE > g7_cubed}")

    # Order-of-elements sanity: 1 has order 1, 9 has order 2 (9^2 = 81
    # ≡ 1), 3 and 7 have order 4. So generators are exactly {3, 7}.
    def order(x):
        k, y = 1, x % 10
        while y != 1:
            y = (y * x) % 10
            k += 1
            if k > 10:
                return -1
        return k

    orders = {x: order(x) for x in C}
    print(f"  orders of elements of C: {orders}")
    generators = {x for x in C if orders[x] == 4}
    print(f"  primitive roots: {sorted(generators)} (expected {{3, 7}})")

    ok = (
        g3_cubed == 7
        and g7_cubed == 3
        and BALANCE < g3_cubed
        and BALANCE > g7_cubed
        and generators == {3, 7}
        and orders[1] == 1
        and orders[9] == 2
    )
    print(f"  Theorem 5.1 verified: {ok}")
    return ok


# === Check 8: CREATION orbit ===
def check_creation_orbit():
    hr("Check 8: CREATION orbit 1 -> 3 -> 9 -> 7 -> 1 under x3")
    orbit = [1]
    x = 1
    for _ in range(4):
        x = (x * 3) % 10
        orbit.append(x)
    expected = [1, 3, 9, 7, 1]
    ok = orbit == expected
    print(f"  orbit of 1 under x3: {orbit}")
    print(f"  expected {expected}: {ok}")
    return ok


# === Check 9: DISSOLUTION orbit ===
def check_dissolution_orbit():
    hr("Check 9: DISSOLUTION orbit 2 -> 6 -> 8 -> 4 -> 2 under x3")
    orbit = [2]
    x = 2
    for _ in range(4):
        x = (x * 3) % 10
        orbit.append(x)
    expected = [2, 6, 8, 4, 2]
    ok = orbit == expected
    print(f"  orbit of 2 under x3: {orbit}")
    print(f"  expected {expected}: {ok}")
    return ok


def main():
    print("# J30 verification — Sanders & Gish 2026")
    print("# Self-contained (stdlib only). Verifies:")
    print("#   - (Z/10Z)* sub-magma closure;")
    print("#   - TSML / BHML restriction to C x C;")
    print("#   - size-4 enumeration (78 TSML, 1 BHML, 1 joint);")
    print("#   - C != joint 4-core (intersection = {7, 9});")
    print("#   - generator-selection g = 3.")

    table = ("Check 1: units closed under x mod 10",
             "Check 2: cyclic group of order 4 from g = 3",
             "Check 3: CL_TSML on C x C (Theorem 3.1)",
             "Check 4: CL_BHML on C x C (Proposition 4.1)",
             "Check 5: size-4 enumeration (Theorem 4.3)",
             "Check 6: C vs joint 4-core (intersection = {7, 9})",
             "Check 7: generator g = 3 (Theorem 5.1)",
             "Check 8: CREATION orbit 1 -> 3 -> 9 -> 7 -> 1",
             "Check 9: DISSOLUTION orbit 2 -> 6 -> 8 -> 4 -> 2")

    results = [
        check_units_closed_mod10(),
        check_cyclic_generator(),
        check_tsml_on_C(),
        check_bhml_on_C(),
        check_size4_enumeration(),
        check_contrast(),
        check_generator_selection(),
        check_creation_orbit(),
        check_dissolution_orbit(),
    ]

    hr("Summary")
    for name, ok in zip(table, results):
        sym = "PASS" if ok else "FAIL"
        print(f"  {sym:4s}  {name}")

    n_pass = sum(1 for r in results if r)
    n_total = len(results)
    print()
    print(f"  {n_pass}/{n_total} PASS")
    return 0 if n_pass == n_total else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
