r"""verify_J32_d4_orbits.py

Standalone, self-contained verifier for J32 — Operadic $D_4$ Orbit Structure on
the Non-Associative Locus of TSML on $\mathbb{Z}/10\mathbb{Z}$.

CENTRAL CLAIMS VERIFIED (all at machine precision; no floating point):

  C1. The canonical TSML_RAW table on Z/10Z has exactly 126 non-associative
      ordered triples (a, b, c), i.e. T(T(a,b),c) != T(a,T(b,c)).

  C2. The dihedral group D_4 = <P_56, sigma^3> generated by the transposition
      P_56 = (5 6) and the order-2 element sigma^3 = (1 5)(2 6)(4 7) of the
      sigma-permutation 6-cycle on (Z/10Z)* has order exactly 8.

  C3. The diagonal action of D_4 on the 126 non-associative triples partitions
      the locus into exactly 67 orbits with size distribution

           |orbit|     # orbits
              1           44
              2            7
              3            4
              4           10
              8            2

      Sum check: 44*1 + 7*2 + 4*3 + 10*4 + 2*8 = 126.

  C4. Bracketing-pair coherence (necessary condition for any D_4-equivariant
      fuse rule with values in {a, b, c, L(t), R(t)}): exactly 16 of the 67
      orbits FAIL the coherence test. Hence no such D_4-equivariant rule
      exists (Theorem A of the manuscript).

  C5. Dropping the sigma^3 generator, the locus partitions under <P_56> into
      exactly 98 orbits (70 singletons + 28 doubletons), all of which are
      P_56-coherent. Hence a P_56-equivariant fuse rule does exist
      (Theorem B of the manuscript).

  C6. 4-core arity-3 closure: among the 4**3 = 64 ordered triples drawn from
      the 4-core C = {0, 7, 8, 9}, all 64 bracketings (left and right) take
      values in C. Exactly 8 of the 64 are non-associative.

The script depends only on the Python standard library (json, itertools,
collections). Runtime < 1 s on a standard laptop. Deterministic.

License: CC-BY-4.0 (the script in this submission bundle is CC-BY-4.0 for
journal compatibility; the umbrella project is 7SiTe v2.1).

Author lane: Sanders + Gish only.
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from itertools import product
from pathlib import Path
from typing import Dict, FrozenSet, Iterable, List, Tuple

# ---------------------------------------------------------------------------
# Canonical TSML_RAW table on Z/10Z (per CL_BIT_PATTERN of the codebase
# `Gen13/targets/foundations/cl.py`; reproduced verbatim from the J32
# manuscript Appendix A and from the verified WP109/WP112 source files).
# ---------------------------------------------------------------------------
TSML_ROWS = [
    "0000000700",
    "0737777777",
    "0377477779",
    "0777777773",
    "0747777787",
    "0777777777",
    "0777777777",
    "7777777777",
    "0777877777",
    "0797377777",
]
TSML: List[List[int]] = [[int(c) for c in row] for row in TSML_ROWS]
N = 10  # Z/10Z


def t(a: int, b: int) -> int:
    """Binary TSML composition on Z/10Z."""
    return TSML[a][b]


def left_bracket(a: int, b: int, c: int) -> int:
    """L(a,b,c) = T(T(a,b), c)."""
    return t(t(a, b), c)


def right_bracket(a: int, b: int, c: int) -> int:
    """R(a,b,c) = T(a, T(b,c))."""
    return t(a, t(b, c))


def is_associative(a: int, b: int, c: int) -> bool:
    return left_bracket(a, b, c) == right_bracket(a, b, c)


# ---------------------------------------------------------------------------
# C1: enumerate the non-associative triples on Z/10Z under TSML_RAW.
# ---------------------------------------------------------------------------
def enumerate_nonassoc() -> List[Tuple[int, int, int]]:
    return [
        (a, b, c)
        for a in range(N)
        for b in range(N)
        for c in range(N)
        if not is_associative(a, b, c)
    ]


# ---------------------------------------------------------------------------
# C2: the dihedral group D_4 = <P_56, sigma^3>.
# ---------------------------------------------------------------------------
def identity_perm() -> Dict[int, int]:
    return {i: i for i in range(N)}


def p56_perm() -> Dict[int, int]:
    """P_56 = (5 6): swap operators 5 (BALANCE) and 6 (CHAOS); fixes all
    other elements."""
    p = identity_perm()
    p[5], p[6] = 6, 5
    return p


def sigma3_perm() -> Dict[int, int]:
    """sigma^3 = (0)(3)(8)(9)(1 5)(2 6)(4 7): the order-2 element of the
    sigma 6-cycle on the units."""
    p = identity_perm()
    p[1], p[5] = 5, 1
    p[2], p[6] = 6, 2
    p[4], p[7] = 7, 4
    return p


def compose(p1: Dict[int, int], p2: Dict[int, int]) -> Dict[int, int]:
    """(p1 . p2)(x) = p1(p2(x))."""
    return {x: p1[p2[x]] for x in p2}


def perm_key(p: Dict[int, int]) -> Tuple[Tuple[int, int], ...]:
    return tuple((i, p[i]) for i in range(N))


def generate_group(gens: List[Dict[int, int]]) -> Dict[Tuple[Tuple[int, int], ...], Dict[int, int]]:
    """Brute-force closure of a finite permutation group from generators."""
    elements: Dict[Tuple[Tuple[int, int], ...], Dict[int, int]] = {}
    identity = identity_perm()
    elements[perm_key(identity)] = identity
    frontier = [identity]
    while frontier:
        new_frontier: List[Dict[int, int]] = []
        for g in frontier:
            for h in gens:
                composed = compose(g, h)
                k = perm_key(composed)
                if k not in elements:
                    elements[k] = composed
                    new_frontier.append(composed)
        frontier = new_frontier
    return elements


# ---------------------------------------------------------------------------
# Diagonal D_4 action on triples, orbit decomposition, and
# bracketing-pair coherence check.
# ---------------------------------------------------------------------------
def diag_action(g: Dict[int, int], triple: Tuple[int, int, int]) -> Tuple[int, int, int]:
    a, b, c = triple
    return (g[a], g[b], g[c])


def restricted_orbit(
    triple: Tuple[int, int, int],
    group: Dict[Tuple[Tuple[int, int], ...], Dict[int, int]],
    locus: set,
) -> FrozenSet[Tuple[int, int, int]]:
    """Orbit of `triple` under the group action, restricted to `locus`."""
    return frozenset(
        diag_action(g, triple) for g in group.values() if diag_action(g, triple) in locus
    )


def orbit_decomposition(
    triples: List[Tuple[int, int, int]],
    group: Dict[Tuple[Tuple[int, int], ...], Dict[int, int]],
) -> List[FrozenSet[Tuple[int, int, int]]]:
    """Partition `triples` into restricted orbits under the group."""
    locus = set(triples)
    seen: set = set()
    orbits: List[FrozenSet[Tuple[int, int, int]]] = []
    for triple in triples:
        if triple in seen:
            continue
        orb = restricted_orbit(triple, group, locus)
        if orb:
            orbits.append(orb)
            seen.update(orb)
    return orbits


def bracketing_pair(triple: Tuple[int, int, int]) -> Tuple[int, int]:
    """Unordered (L, R) pair as a sorted tuple."""
    L = left_bracket(*triple)
    R = right_bracket(*triple)
    return tuple(sorted((L, R)))


def orbit_is_coherent(
    orbit: FrozenSet[Tuple[int, int, int]],
    group: Dict[Tuple[Tuple[int, int], ...], Dict[int, int]],
) -> bool:
    """Bracketing-pair coherence: for any g taking t to t' in the orbit,
    the multiset {g(L(t)), g(R(t))} must equal {L(t'), R(t')}."""
    elements = list(orbit)
    if len(elements) <= 1:
        return True
    base = elements[0]
    Lb = left_bracket(*base)
    Rb = right_bracket(*base)
    for t_other in elements[1:]:
        # Find some g with diag_action(g, base) = t_other.
        found_g = None
        for g in group.values():
            if diag_action(g, base) == t_other:
                found_g = g
                break
        if found_g is None:
            return False
        expected = {found_g[Lb], found_g[Rb]}
        actual = {left_bracket(*t_other), right_bracket(*t_other)}
        if expected != actual:
            return False
    return True


# ---------------------------------------------------------------------------
# Main verification routine: emits the 6 claim verdicts.
# ---------------------------------------------------------------------------
def main() -> int:
    print("J32 verification: D_4 = <P_56, sigma^3> orbits on the non-associative")
    print("locus of TSML_RAW on Z/10Z.")
    print("=" * 72)

    failures = 0

    # ------------------------------------------------------------------ C1
    triples = enumerate_nonassoc()
    print()
    print(f"[C1] Non-associative ordered triples: |N| = {len(triples)}")
    if len(triples) != 126:
        print("    FAIL: expected 126.")
        failures += 1
    else:
        print("    PASS.")

    # Cross-check against the bundled JSON, if present.
    json_path = Path(__file__).parent.parent / "nonassoc_triples.json"
    if json_path.exists():
        with open(json_path, "r") as f:
            json_triples = json.load(f)
        json_set = {(d["a"], d["b"], d["c"]) for d in json_triples}
        if json_set != set(triples):
            print("    FAIL: bundled JSON does not match computed locus.")
            failures += 1
        else:
            print(f"    PASS (JSON cross-check: {len(json_triples)} triples agree).")

    # ------------------------------------------------------------------ C2
    P56 = p56_perm()
    S3 = sigma3_perm()
    D4 = generate_group([P56, S3])
    print()
    print(f"[C2] |D_4| = |<P_56, sigma^3>| = {len(D4)}")
    if len(D4) != 8:
        print("    FAIL: expected 8.")
        failures += 1
    else:
        # Order-2 / order-4 spectrum check for D_4.
        order_counter: Counter = Counter()
        identity = identity_perm()
        identity_k = perm_key(identity)
        for k, g in D4.items():
            order = 1
            g_pow = g
            while perm_key(g_pow) != identity_k:
                g_pow = compose(g_pow, g)
                order += 1
            order_counter[order] += 1
        if order_counter == Counter({1: 1, 2: 5, 4: 2}):
            print("    PASS (order spectrum {1:1, 2:5, 4:2} matches D_4).")
        else:
            print(f"    FAIL: order spectrum {dict(order_counter)} != D_4 expectation.")
            failures += 1

    # ------------------------------------------------------------------ C3
    orbits = orbit_decomposition(triples, D4)
    sizes = Counter(len(o) for o in orbits)
    sum_check = sum(s * c for s, c in sizes.items())
    print()
    print(f"[C3] D_4 orbit count: {len(orbits)}")
    print(f"     Size distribution: {dict(sorted(sizes.items()))}")
    print(f"     Size-weighted sum: {sum_check}")
    expected = {1: 44, 2: 7, 3: 4, 4: 10, 8: 2}
    if dict(sizes) == expected and len(orbits) == 67 and sum_check == 126:
        print("     PASS (orbit count 67; distribution (44,7,4,10,2); sum 126).")
    else:
        print(f"     FAIL: expected distribution {expected}, 67 orbits, sum 126.")
        failures += 1

    # ------------------------------------------------------------------ C4
    incoherent = [o for o in orbits if not orbit_is_coherent(o, D4)]
    print()
    print(f"[C4] D_4-incoherent orbits: {len(incoherent)} / {len(orbits)}")
    if len(incoherent) == 16:
        print("     PASS (16 obstructed orbits; matches manuscript Theorem A).")
    else:
        print("     FAIL: expected 16.")
        failures += 1

    # ------------------------------------------------------------------ C5
    P56_group = generate_group([P56])
    p56_orbits = orbit_decomposition(triples, P56_group)
    p56_sizes = Counter(len(o) for o in p56_orbits)
    p56_incoherent = [o for o in p56_orbits if not orbit_is_coherent(o, P56_group)]
    print()
    print(f"[C5] <P_56> orbit count: {len(p56_orbits)}")
    print(f"     Size distribution: {dict(sorted(p56_sizes.items()))}")
    print(f"     <P_56>-incoherent orbits: {len(p56_incoherent)}")
    if (
        len(p56_orbits) == 98
        and p56_sizes == Counter({1: 70, 2: 28})
        and len(p56_incoherent) == 0
    ):
        print("     PASS (98 orbits: 70 singletons + 28 doubletons; all coherent).")
    else:
        print("     FAIL: expected 98 orbits (70+28), all coherent.")
        failures += 1

    # ------------------------------------------------------------------ C6
    C = {0, 7, 8, 9}  # 4-core
    fourcore_triples = list(product(sorted(C), repeat=3))
    in_core = 0
    out_core = 0
    nonassoc_in_core = 0
    for triple in fourcore_triples:
        L = left_bracket(*triple)
        R = right_bracket(*triple)
        if L in C and R in C:
            in_core += 1
        else:
            out_core += 1
        if L != R:
            nonassoc_in_core += 1
    print()
    print(f"[C6] 4-core arity-3 closure: 4^3 = {len(fourcore_triples)} triples.")
    print(f"     In-core bracketings (both L,R in C): {in_core}")
    print(f"     Out-of-core bracketings: {out_core}")
    print(f"     Non-associative 4-core triples: {nonassoc_in_core}")
    if in_core == 64 and out_core == 0 and nonassoc_in_core == 8:
        print("     PASS (4-core closed under arity-3 fuse; 8 of 64 non-associative).")
    else:
        print("     FAIL: expected 64 in-core / 0 out / 8 non-associative.")
        failures += 1

    # ------------------------------------------------------------------
    print()
    print("=" * 72)
    if failures == 0:
        print("ALL 6 CLAIMS PASS.")
        return 0
    print(f"TOTAL FAILURES: {failures}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
