"""
STAGE 4: Correct the closure analysis.

Stage 2 was WRONG — it did least-squares projection which can give low
residuals even when closure fails. Let me check closure ACCURATELY.

Correct approach: take the Lie algebra GENERATED by the 8 A_i's
(closing under commutators repeatedly) and see what its actual dimension is.
"""
import numpy as np

CL = [[0,0,0,0,0,0,0,7,0,0],[0,7,3,7,7,7,7,7,7,7],[0,3,7,7,4,7,7,7,7,9],
      [0,7,7,7,7,7,7,7,7,3],[0,7,4,7,7,7,7,7,8,7],[0,7,7,7,7,7,7,7,7,7],
      [0,7,7,7,7,7,7,7,7,7],[7,7,7,7,7,7,7,7,7,7],[0,7,7,7,8,7,7,7,7,7],
      [0,7,9,3,7,7,7,7,7,7]]
OP = ['VOID','LATTICE','COUNTER','PROGRESS','COLLAPSE',
      'BALANCE','CHAOS','HARMONY','BREATH','RESET']

def action_matrix(op):
    M = np.zeros((10, 10), dtype=int)
    for j in range(10):
        M[CL[op][j], j] = 1
    return M

L = [action_matrix(op) for op in range(10)]

def comm(X, Y):
    return X @ Y - Y @ X

def to_vec(M):
    return M.flatten().astype(float)

def dim_of_span(matrices, tol=1e-8):
    if not matrices: return 0
    V = np.stack([to_vec(m) for m in matrices], axis=1)
    return np.linalg.matrix_rank(V, tol=tol)

def close_under_commutator(gens, max_iter=10):
    """Compute the Lie algebra generated by gens."""
    current = list(gens)
    for iteration in range(max_iter):
        old_dim = dim_of_span(current)
        new_mats = []
        for i in range(len(current)):
            for j in range(i+1, len(current)):
                c = comm(current[i], current[j])
                if np.linalg.norm(c) > 1e-9:
                    new_mats.append(c)
        test = current + new_mats
        new_dim = dim_of_span(test)
        if new_dim == old_dim:
            return current, old_dim
        # reduce to independent basis
        V = np.stack([to_vec(m) for m in test], axis=1)
        # find pivot columns via QR
        Q, R = np.linalg.qr(V)
        indep_idx = []
        used = set()
        for col in range(V.shape[1]):
            vec = V[:, col]
            test_V = V[:, indep_idx + [col]]
            if np.linalg.matrix_rank(test_V, tol=1e-8) == len(indep_idx) + 1:
                indep_idx.append(col)
        current = [test[k] for k in indep_idx]
    return current, dim_of_span(current)

# ─────────────────────────────────────────────────
# Test various generating sets
# ─────────────────────────────────────────────────
print("="*70)
print("ACTUAL Lie algebras generated by subsets of TIG action matrices")
print("="*70)

tests = [
    ('all 10 L (raw)',         [L[op] for op in range(10)]),
    ('8 non-center L',         [L[op] for op in [1,2,3,4,5,6,8,9]]),
    ('8 antisymmetrized A',    [L[op] - L[op].T for op in [1,2,3,4,5,6,8,9]]),
    ('6 flow A',               [L[op] - L[op].T for op in [1,2,3,4,6,8]]),
    ('4 pairs sums',           [(L[1]-L[1].T)+(L[4]-L[4].T),
                                (L[2]-L[2].T)+(L[3]-L[3].T),
                                (L[6]-L[6].T)+(L[8]-L[8].T),
                                (L[5]-L[5].T)+(L[9]-L[9].T)]),
    ('4 pairs diffs',          [(L[1]-L[1].T)-(L[4]-L[4].T),
                                (L[2]-L[2].T)-(L[3]-L[3].T),
                                (L[6]-L[6].T)-(L[8]-L[8].T),
                                (L[5]-L[5].T)-(L[9]-L[9].T)]),
]

print(f"\n  {'generating set':<30s}  {'initial dim':>12s}  {'closure dim':>12s}")
for label, gens in tests:
    init_dim = dim_of_span(gens)
    _, closed_dim = close_under_commutator(gens)
    match = ""
    if closed_dim == 8: match = " = dim su(3)"
    elif closed_dim == 3: match = " = dim so(3)"
    elif closed_dim == 6: match = " = dim so(4)=su(2)⊕su(2)"
    elif closed_dim == 15: match = " = dim su(4)=so(6)"
    elif closed_dim == 21: match = " = dim so(7)"
    elif closed_dim == 28: match = " = dim so(8)"
    elif closed_dim == 36: match = " = dim so(9)"
    elif closed_dim == 45: match = " = dim so(10)"
    elif closed_dim == 10: match = " = dim sp(4) or so(5)"
    elif closed_dim == 100: match = " = dim gl(10)"
    print(f"  {label:<30s}  {init_dim:>12d}  {closed_dim:>12d}{match}")

# ─────────────────────────────────────────────────
# Key question: does 8 generators close into exactly 8?
# If YES → we have a bona fide 8-dim Lie algebra = candidate su(3)
# If NO → the 8 generators lie inside a larger Lie algebra
# ─────────────────────────────────────────────────
A8 = [L[op] - L[op].T for op in [1,2,3,4,5,6,8,9]]
_, dim_closed = close_under_commutator(A8)
print(f"\n8 antisymmetrized generators close into dim = {dim_closed}")

if dim_closed == 8:
    print("  → They form an exact 8-dim Lie algebra.")
    print("  → Next step: check if isomorphic to su(3).")
elif dim_closed > 8:
    print(f"  → They generate a larger {dim_closed}-dim algebra.")
    print(f"  → The 8 A's are inside it but don't form a subalgebra.")
    print(f"  → Keep searching for the right 8-dim subalgebra.")
